#!/usr/bin/env bash

user=FORAGES
repo=FORAGES.github.io

make -C ./vendor
./build

rm -rf "${repo}"
cp -r dist "${repo}"

cd "${repo}"
git init
git remote add origin "git@github.com:${user}/${repo}.git"
git add .
git commit -m "Deployed `date`."
git push -f origin master

cd ..
rm -rf "${repo}"
